<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<link type="image/x-icon" href="https://cdn1.alegra.com/images/favicon.ico">
		<title>Alegra Contacts</title>
		<?php
            echo $this->headLink()
                ->appendStylesheet('/ext4/resources/css/ext-all.css')
                ->appendStylesheet('/resources/css/app.css');
            echo $this->headScript()
                ->appendFile('ext4/ext-all-debug.js')
                ->appendFile('app.js');
    ?>
		<script type="text/javascript" src="https://cdn1.alegra.com/long-term/compressed/ext-lang-es.js"></script>
	</head>
	<body>
		<?php  echo $this->layout()->content ?>
	</body>
</html>
